pipeline {
    agent any

    environment {
        SONAR_HOME = tool "Sonar"
    }

    stages {
        stage("Checkout repository"){
            steps{
                git url: "https://github.com/rupesh-hub/COURSE-MANAGEMENT-SYSTEM.git", branch: "main"
            }
        }

        stage("SonarQube Quality Analysis") {
            steps {
                withSonarQubeEnv("Sonar") {
                    sh '''
                        cd backend
                        $SONAR_HOME/bin/sonar-scanner \
                            -Dsonar.projectName=course-management-system \
                            -Dsonar.projectKey=course-management-system
                    '''
                }
            }
        }

    }

}